apiVersion: v1
kind: ConfigMap
metadata:
  name: init-wpuser-configmap
  namespace: rockstar-namespace
data:
  init-wordpress-database.sql: |
    CREATE DATABASE IF NOT EXISTS wordpress;
    CREATE USER 'wordpress'@'%' IDENTIFIED BY 'wordpress';
    GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'%';
