apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
  namespace: rockstar-namespace
init:
  scriptSource:
    local:
      path: ./scripts
spec:
  version: "5.7.25"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
