apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
  namespace: rockstar-namespace
spec:
  version: "5.7.25"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      containers:
        volumeMounts:
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: init-wpuser-configmap
            namespace: rockstar-namespace
  init:
    scriptSource:
      configMap:
        name: init-wpuser-configmap
        namespace: rockstar-namespace
